apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
  app.kubernetes.io/name: alb-ingress-controller
 name: rbdeploy
 namespae: kube-system
spec:
 replicas: 3
 selector:
  matchLabels:
   app.kubernetes.io/name: alb-ingress-controller
 template:
  metadata:
   labels:
    app.kubernetes.io/name: alb-ingress-controller
  spec:
   containers:
     - name: alb-ingress-controller
	   args: 
	   image: docker.io/amazon/aws-alb-ingress-controller:v1.1.4
   serviceAccountName: alb-ingress-controller
	